config/routes.rb
Rails.application.routes.draw do

  root 'home#top'

  devise_for :shops,skip: [:passwords], controllers: {
    registrations: "shop/registrations",
    sessions: 'shop/sessions'
  }

  devise_for :managements,skip: [:passwords], controllers: {
    registrations: "management/registrations",
    sessions: 'management/sessions'
  }

  devise_scope :shop do
    post 'shops/guest_sign_in', to: 'shops/sessions#guest_sign_in'
  end

  devise_scope :management do
    post 'managements/guest_sign_in', to: 'managements/sessions#guest_sign_in'
  end

  scope module: :shop do
    resources :notifications, only: :index do
        delete "all_destroy"
      end
    resources :shops, only: [:edit, :update] do
      collection do
        get "my_page" => "shops#show"
      end
    end
    resources :posts do
      resources :comment_reviews, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      collection do
        get "search"
      end
    end
    resources :groups do
      get "join" => "groups#join"
      get "new/mail" => "groups#new_mail"
      get "send/mail" => "groups#send_mail"
      delete "all_destroy" => "groups#all_destroy"
    end
    resources :mother_father_gifts
    resources :summer_gifts
    resources :year_end_gifts
    resources :day_of_the_oxes
    resources :ehomakis
    resources :christmases
    get "chat/:id" => "chats#show", as: "chat"
    resources :chats, only: [:create]
  end

    namespace :management do
      resources :managements, only: [:edit, :update] do
        collection do
          get "my_page" => "managements#show"
        end
      end
      resources :posts do
        resource :management_favorites, only: [:create, :destroy]
      end
    end
end

app/controllers/shop/chats_controller.rb
class Shop::ChatsController < ApplicationController
  before_action :authenticate_shop!

  def show
    @shop = Shop.find(params[:id])
    rooms = current_shop.shop_rooms.pluck(:room_id)
    shop_rooms = ShopRoom.find_by(shop_id: @shop.id,room_id: rooms)

    unless shop_rooms.nil?
      @room = shop_rooms.room
    else
      @room = Room.new
      @room.save
      ShopRoom.create(shop_id: current_shop.id, room_id: @room.id)
      ShopRoom.create(shop_id: @shop.id, room_id: @room.id)
    end
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end

  def create
    @chat = current_shop.chats.new(chat_params)
    if @chat.save
      @chat.create_notification_chat!(current_shop, @chat.id, @chat.room_id, @chat.room.shop_rooms.where.not(shop_id: current_shop.id).first.shop_id)
      redirect_to request.referer
    else
      redirect_to request.referer,alert: "メッセージを入力してください"
    end
  end

  private

  def chat_params
    params.require(:chat).permit(:message, :room_id, images: [] )
  end

end

app/controllers/shop/christmases_controller.rb
class Shop::ChristmasesController < ApplicationController
  before_action :user_authenticate

  def index

    @christmas = Christmas.new
    @shop_total_amount = 0
    @shop_tptal_booking_target = 0
    @shop_store_sales_amount = 0

    @current_year = params[:current_year].present? ? params[:current_year] : Time.zone.now.year
    @all_christmases = Christmas.all
    @christmases = @all_christmases.where(year: @current_year)
    @christmases = @christmases.order(booking_amount: :asc) if params[:sort_amount] == "booking_amount_asc"
    @christmases = @christmases.order(total_amount: :asc) if params[:sort_amount] == "total_amount_asc"
    @christmases = @christmases.order(booking_amount: :desc) if params[:sort_amount] == "booking_amount_desc"
    @christmases = @christmases.order(total_amount: :desc) if params[:sort_amount] == "total_amount_desc"
    @christmases = @christmases.page(params[:page])

  end

  def create
    @christmas = Christmas.new(christmas_params)
    @christmas.shop_id = current_shop.id
    if @christmas.save
      redirect_to christmases_path, notice: "投稿に成功しました"
    else
      @shop_total_amount = 0
      @shop_tptal_booking_target = 0
      @shop_store_sales_amount = 0

      @current_year = params[:current_year].present? ? params[:current_year] : Time.zone.now.year
      @all_christmases = Christmas.all
      @christmases = @all_christmases.where(year: @current_year)
      @christmases = @christmases.order(booking_amount: :asc) if params[:sort_amount] == "booking_amount_asc"
      @christmases = @christmases.order(total_amount: :asc) if params[:sort_amount] == "total_amount_asc"
      @christmases = @christmases.order(booking_amount: :desc) if params[:sort_amount] == "booking_amount_desc"
      @christmases = @christmases.order(total_amount: :desc) if params[:sort_amount] == "total_amount_desc"
      @christmases = @christmases.page(params[:page])
      render :index
    end
  end

  def update
    @christmas = Christmas.find(params[:id])
    if @christmas.update(christmas_params)
      redirect_to christmases_path, notice: "投稿を更新しました"
    else
      @shop_total_amount = 0
      @shop_tptal_booking_target = 0
      @shop_store_sales_amount = 0

      @current_year = params[:current_year].present? ? params[:current_year] : Time.zone.now.year
      @all_christmases = Christmas.all
      @christmases = @all_christmases.where(year: @current_year)
      @christmases = @christmases.order(booking_amount: :asc) if params[:sort_amount] == "booking_amount_asc"
      @christmases = @christmases.order(total_amount: :asc) if params[:sort_amount] == "total_amount_asc"
      @christmases = @christmases.order(booking_amount: :desc) if params[:sort_amount] == "booking_amount_desc"
      @christmases = @christmases.order(total_amount: :desc) if params[:sort_amount] == "total_amount_desc"
      @christmases = @christmases.page(params[:page])
      render :index
    end
  end

  def destroy
    @christmas = Christmas.find(params[:id])
    @christmas.destroy
    redirect_to christmases_path, notice: "投稿を削除しました"
  end


  def edit
    @christmas = Christmas.find(params[:id])
  end

  private

  def user_authenticate
    if shop_signed_in? || management_signed_in?
    else
      redirect_to root_path
    end
  end


  def christmas_params
    params.require(:christmas).permit(:year, :booking_target,:booking_amount, :target_amount,  :store_sales_amount, :total_amount, :shop_id, :ff_amount)
  end
end

app/controllers/shop/comment_reviews_controller.rb
class Shop::CommentReviewsController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    comment = current_management.comment_reviews.new(comment_review_params)
    comment.post_id = post.id
    comment.save
    redirect_to post_path(post), notice: "コメントの投稿に成功しました"
  end

  def destroy
    CommentReview.find(params[:id]).destroy
    redirect_to post_path(params[:post_id]), notice: "コメントを削除しました"
  end

  private

  def comment_review_params
    params.require(:comment_review).permit(:comment, :star)
  end
end

app/controllers/shop/confirmations_controller.rb
# frozen_string_literal: true

class Shop::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/shop/day_of_the_oxes_controller.rb
class Shop::DayOfTheOxesController < ApplicationController
  before_action :user_authenticate
  
  def index

    @day_of_the_ox = DayOfTheOx.new
    @shop_total_amount = 0
    @shop_tptal_booking_target = 0
    @shop_store_sales_amount = 0

    @current_year = params[:current_year].present? ? params[:current_year] : Time.zone.now.year
    @all_day_of_the_oxes = DayOfTheOx.all
    @day_of_the_oxes = @all_day_of_the_oxes.where(year: @current_year)
    @day_of_the_oxes = @day_of_the_oxes.order(booking_amount: :asc) if params[:sort_amount] == "booking_amount_asc"
    @day_of_the_oxes = @day_of_the_oxes.order(total_amount: :asc) if params[:sort_amount] == "total_amount_asc"
    @day_of_the_oxes = @day_of_the_oxes.order(booking_amount: :desc) if params[:sort_amount] == "booking_amount_desc"
    @day_of_the_oxes = @day_of_the_oxes.order(total_amount: :desc) if params[:sort_amount] == "total_amount_desc"
    @day_of_the_oxes = @day_of_the_oxes.page(params[:page])
  end

  def create
    @day_of_the_ox = DayOfTheOx.new(day_of_the_ox_params)
    @day_of_the_ox.shop_id = current_shop.id
    if @day_of_the_ox.save
      redirect_to day_of_the_oxes_path, notice: "投稿に成功しました"
    else
      @shop_total_amount = 0
      @shop_tptal_booking_target = 0
      @shop_store_sales_amount = 0

      @current_year = params[:current_year].present? ? params[:current_year] : Time.zone.now.year
      @all_day_of_the_oxes = DayOfTheOx.all
      @day_of_the_oxes = @all_day_of_the_oxes.where(year: @current_year)
      @day_of_the_oxes = @day_of_the_oxes.order(booking_amount: :asc) if params[:sort_amount] == "booking_amount_asc"
      @day_of_the_oxes = @day_of_the_oxes.order(total_amount: :asc) if params[:sort_amount] == "total_amount_asc"
      @day_of_the_oxes = @day_of_the_oxes.order(booking_amount: :desc) if params[:sort_amount] == "booking_amount_desc"
      @day_of_the_oxes = @day_of_the_oxes.order(total_amount: :desc) if params[:sort_amount] == "total_amount_desc"
      @day_of_the_oxes = @day_of_the_oxes.page(params[:page])
      render :index
    end
  end

  def update
    @day_of_the_ox = DayOfTheOx.find(params[:id])
    if @day_of_the_ox.update(day_of_the_ox_params)
      redirect_to day_of_the_oxes_path, notice: "投稿を更新しました"
    else
      @shop_total_amount = 0
      @shop_tptal_booking_target = 0
      @shop_store_sales_amount = 0

      @current_year = params[:current_year].present? ? params[:current_year] : Time.zone.now.year
      @all_day_of_the_oxes = DayOfTheOx.all
      @day_of_the_oxes = @all_day_of_the_oxes.where(year: @current_year)
      @day_of_the_oxes = @day_of_the_oxes.order(booking_amount: :asc) if params[:sort_amount] == "booking_amount_asc"
      @day_of_the_oxes = @day_of_the_oxes.order(total_amount: :asc) if params[:sort_amount] == "total_amount_asc"
      @day_of_the_oxes = @day_of_the_oxes.order(booking_amount: :desc) if params[:sort_amount] == "booking_amount_desc"
      @day_of_the_oxes = @day_of_the_oxes.order(total_amount: :desc) if params[:sort_amount] == "total_amount_desc"
      @day_of_the_oxes = @day_of_the_oxes.page(params[:page])
      render :index
    end
  end

  def destroy
    @day_of_the_ox = DayOfTheOx.find(params[:id])
    @day_of_the_ox.destroy
    redirect_to day_of_the_oxes_path, notice: "投稿を削除しました"
  end

  private
  
  def user_authenticate
    if shop_signed_in? || management_signed_in?
    else
      redirect_to root_path
    end
  end
  
  def day_of_the_ox_params
    params.require(:day_of_the_ox).permit(:year, :booking_target,:booking_amount, :target_amount,  :store_sales_amount, :total_amount, :shop_id)
  end
end

app/controllers/shop/ehomakis_controller.rb
class Shop::EhomakisController < ApplicationController
  before_action :user_authenticate

  def index

    @ehomaki = Ehomaki.new
    @shop_total_amount = 0
    @shop_tptal_booking_target = 0
    @shop_store_sales_amount = 0

    @current_year = params[:current_year].present? ? params[:current_year] : Time.zone.now.year
    @all_ehomakis = Ehomaki.all
    @ehomakis = @all_ehomakis.where(year: @current_year)
    @ehomakis = @ehomakis.order(booking_amount: :asc) if params[:sort_amount] == "booking_amount_asc"
    @ehomakis = @ehomakis.order(total_amount: :asc) if params[:sort_amount] == "total_amount_asc"
    @ehomakis = @ehomakis.order(booking_amount: :desc) if params[:sort_amount] == "booking_amount_desc"
    @ehomakis = @ehomakis.order(total_amount: :desc) if params[:sort_amount] == "total_amount_desc"
    @ehomakis = @ehomakis.page(params[:page])
  end

  def create
    @ehomaki = Ehomaki.new(ehomaki_params)
    @ehomaki.shop_id = current_shop.id
    if @ehomaki.save
      redirect_to ehomakis_path, notice: "投稿に成功しました"
    else

      @shop_total_amount = 0
      @shop_tptal_booking_target = 0
      @shop_store_sales_amount = 0

      @current_year = params[:current_year].present? ? params[:current_year] : Time.zone.now.year
      @all_ehomakis = Ehomaki.all
      @ehomakis = @all_ehomakis.where(year: @current_year)
      @ehomakis = @ehomakis.order(booking_amount: :asc) if params[:sort_amount] == "booking_amount_asc"
      @ehomakis = @ehomakis.order(total_amount: :asc) if params[:sort_amount] == "total_amount_asc"
      @ehomakis = @ehomakis.order(booking_amount: :desc) if params[:sort_amount] == "booking_amount_desc"
      @ehomakis = @ehomakis.order(total_amount: :desc) if params[:sort_amount] == "total_amount_desc"
      @ehomakis = @ehomakis.page(params[:page])
      render :index
    end
  end

  def update
    @ehomaki = Ehomaki.find(params[:id])
    if @ehomaki.update(ehomaki_params)
      redirect_to ehomakis_path, notice: "投稿を更新しました"
    else

      @shop_total_amount = 0
      @shop_tptal_booking_target = 0
      @shop_store_sales_amount = 0

      @current_year = params[:current_year].present? ? params[:current_year] : Time.zone.now.year
      @all_ehomakis = Ehomaki.all
      @ehomakis = @all_ehomakis.where(year: @current_year)
      @ehomakis = @ehomakis.order(booking_amount: :asc) if params[:sort_amount] == "booking_amount_asc"
      @ehomakis = @ehomakis.order(total_amount: :asc) if params[:sort_amount] == "total_amount_asc"
      @ehomakis = @ehomakis.order(booking_amount: :desc) if params[:sort_amount] == "booking_amount_desc"
      @ehomakis = @ehomakis.order(total_amount: :desc) if params[:sort_amount] == "total_amount_desc"
      @ehomakis = @ehomakis.page(params[:page])
      render :index
    end
  end

  def destroy
    @ehomaki = Ehomaki.find(params[:id])
    @ehomaki.destroy
    redirect_to ehomakis_path, notice: "投稿を削除しました"
  end

  private

  def user_authenticate
    if shop_signed_in? || management_signed_in?
    else
      redirect_to root_path
    end
  end

  def ehomaki_params
    params.require(:ehomaki).permit(:year, :booking_target,:booking_amount, :target_amount,  :store_sales_amount, :total_amount, :shop_id)
  end
end

app/controllers/shop/favorites_controller.rb
class Shop::FavoritesController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    favorite = current_shop.favorites.new(post_id: @post.id)
    favorite.save
  end


  def destroy
    @post = Post.find(params[:post_id])
    favorite = current_shop.favorites.find_by(post_id: @post.id)
    favorite.destroy
  end

end

app/controllers/shop/groups_controller.rb
class Shop::GroupsController < ApplicationController
  before_action :authenticate_shop!

  def index
    @groups = Group.all
    @group = Group.new
  end

  def create
    @group = current_shop.owned_groups.new(group_params)
    @group.owner_id = current_shop.id
    @group.shops << current_shop  # @group.shops << current_shop  @group.shopsに追加しているという記述
    if @group.save
      redirect_to groups_path(@group), notice: "グループ作成に成功しました"
    else
      @groups = Group.all
      render :index
    end
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to groups_path, notice: "グループ情報を更新しました"
    else
      render :index
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.shops.delete(current_shop)
    redirect_to groups_path
  end


  def join
    @group = Group.find(params[:group_id])
    @group.shops << current_shop
    redirect_to groups_path
  end

  def all_destroy
    @group = Group.find(params[:group_id])
    if @group.destroy
      redirect_to groups_path, notice: "グループを削除しました"
    end
  end

  def new_mail
    @group = Group.find(params[:id])
  end

  def send_mail
    @group = Group.find(params[:group_id])
    group_shops = @group.shops
    @mail_title = params[:title]
    @mail_content = params[:content]
    ContactMailer.send_mail(@mail_title, @mail_content, group_shops).deliver
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :profile_image, :status)
  end

end

app/controllers/shop/notifications_controller.rb
class Shop::NotificationsController < ApplicationController
  def index
    @notifications = current_shop.passive_notifications.all
    @notifications.where(checked: false).each do |notification|
      notification.update_attribute(:checked, true)
    end
  end

  def all_destroy
    @notifications = current_shop.passive_notifications.all
    @notifications.destroy_all
    redirect_to notifications_path, notice: "通知を全て削除しました"
  end


end

app/controllers/shop/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Shop::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/views/shop/posts/index.html.erb
<div class="d-flex flex-row w-100" style="height: calc(100% - 50px)">
  <!--サイドバーコンテンツ-->
  <%= render "layouts/sidenav" %>
    <div class="container mt-3">
      <div class="row">
        <div class="col">
         <% if  @post.errors.any? %>
           <ul class=" alert alert-danger">
              <%=  @post.errors.count %>件のエラーが発生しました
              <% @post.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
          <% if shop_signed_in? %>
            <div class="row">
              <div class="col mb-3 ">
                <% if current_shop && unchecked_notifications.any? %>
                  <i class="fa fa-circle" style="color: #ff1100;"></i>
                <% end %>
                <%= link_to notifications_path, class: "text-secondary font-weight-bold text-decoration-none" do %>
                  Chat Info <i class="fas fa-comment-medical"></i>
                <% end %>
              </div>
            </div>
          <% end %>
          <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-12">
              <% if shop_signed_in? %>
              <div data-toggle="tooltip" title="投稿する!!">
                <button type="button" class="btn btn-primary  btn-block mb-3 font-weight-bold" data-toggle="modal" data-target="#exampleModal">
                  <i class="fas fa-pen-nib mr-2"></i>Share!!
                </button>
              </div>
              <% end %>
            </div>
            <div class="col-lg-7 col-md-7 col-sm-12">
              <%= search_form_for @search , url: search_posts_path do |f| %>
                <%= f.search_field :name_or_shop_name_or_tag_name_cont , class:"form-control shadow-sm border.border-5", placeholder:"店舗名、カテゴリから検索"%>
              <% end %>
            </div>
          </div>
          <div class="row">
            <div class="col-12 col-lg-2 col-md-12 col-sm-12 mt-2">
              <h5 class=" text-secondary font-weight-bold">投稿数合計 <%= @post_count %>件</h5>
            </div>
            <div class="col-12 col-lg-2 col-md-12 col-sm-12 ">
              <button type="button"class="pt-1 pb-1 rounded border-0 font-weight-bold mb-2"style="background-color: #888b8e; color: #ffffff;"><%= link_to "新着順", posts_path(top: "true"), class: "text-reset text-decoration-none" %></button>
              <button type="button"class="pt-1 pb-1 rounded border-0 font-weight-bold mb-2 ml-2"style="background-color: #888b8e; color: #ffffff;"><%= link_to "登録順", posts_path(old: "true"), class: "text-reset text-decoration-none" %></button>
            </div>
          </div>
          <% @posts.each do |post| %>
            <div class="card mb-1 shadow-sm">
              <div class="card-body  text-secondary font-weight-bold">
                <div class="row">
                  <div class="col-12 col-lg-4 col-md-6 col-sm-12">
                    <%= image_tag post.get_profile_image(300,300),class: "img-fluid"%>
                  </div>
                  <div class="col-12 col-lg-4 col-md-6 col-sm-12">
                    <p class="card-text"><%= post.created_at.strftime("%Y年%-m月%-d日%H時%M分") %></p>
                    <p class="card-text ">役職　<%= post.job %></p>
                    <p class="card-text">スタッフ名　<%= post.name %></p>
                      <div class="row">
                        <div class="col-5 col-lg-5   mt-2">
                          <%= image_tag post.shop.get_profile_image(80,80), class: "rounded img-fluid"%><br>
                        </div>
                        <div =class="col-6 col-lg-6  mt-2 ">
                          <p class="card-text"><%=  post.shop.name %></p>
                          <%= link_to post_path(post),class: "text-decoration-none mr-2" do %>
                            <span data-toggle="tooltip" data-placement="bottom" title="詳細を見る" class=" rounded-circle p-2 shadow-sm"style="background-color: #cdebf3;"><i class="fas fa-search"  style=" color: #39afd1; "></i></span>
                          <% end %>
                          <% if shop_signed_in? %>
                            <% if post.shop_id == current_shop.id %>
                              <span data-toggle="tooltip" data-placement="bottom" title="編集する" ><span class=" rounded-circle p-2 shadow-sm"style="background-color: #dcdefc;"data-toggle="modal" data-target="#exampleModal_<%= post.id %>"><i class="fas fa-edit"  style=" color: #737df5; "></i></span></span>
                              <%= link_to post_path(post), method: :delete,"data-confirm" => "本当に消しますか？",class: "text-decoration-none"  do %>
                                <span data-toggle="tooltip" data-placement="bottom" title="削除する" ><span class=" rounded-circle p-2 shadow-sm ml-1"style=" background-color: #f0b3bf;"><i class="fas fa-eraser" style=" color: #fa5c7c; "></i></span></span>
                              <% end %>
                            <% end %>
                          <% end %>
                        </div>
                      </div>
                  </div>
                  <div class="col-12 col-lg-4 col-md-12 col-sm-12">
                    <p class="card-text">タイトル　<%= post.title %></p>
                    <p class="card-text">カテゴリー　<%=  post.tag.name %></p>
                    <p class="card-text">コメント件数　<%= post.comment_reviews.count %>件</p>
                    <% if shop_signed_in? %>
                      <div id="favorite_buttons_<%= post.id %>">
                        <%= render "shop/posts/favrite", post: post %>
                      </div>
                    <% end %>
                    <% if management_signed_in? %>
                      <div id="management_favorite_buttons_<%= post.id %>">
                        <%= render "shop/posts/management_favorites", post: post %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <!-- Modal -->
            <div class="modal fade" id="exampleModal_<%= post.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">投稿情報を編集する</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <%= form_with model: post, url: post_path(post) do |f| %>
                    <div class="modal-body">
                      <div class="form-group">
                        <%= f.label :title, "タイトル" %>
                        <%= f.text_field :title, class:"form-control" %>
                      </div>
                      <div class="form-group">
                        <%= f.label :appeal, "アピールポイント" %>
                        <%= f.text_area :appeal, rows:'10',placeholder: "自分の頑張ったところを紹介しよう" , class:"form-control"%>
                      </div>
                      <div class="form-group">
                        <%= f.label :job, "役職" %>
                        <%= f.text_field :job, class:"form-control" %>
                      </div>
                      <div class="form-group">
                        <%= f.label :name, "担当者" %>
                        <%= f.text_field :name, class:"form-control" %>
                      </div>
                      <div class="form-group">
                        <%= f.label :ジャンル,class: "col-sm-3 col-form-label" %>
                        <%= f.collection_select :tag_id, Tag.all, :id, :name, class: 'form-control'%>
                      </div>
                      <div class="form-group">
                        <%= f.label :画像 ,class: "col-sm-3 col-form-label " %>
                        <%= f.file_field :profile_image, accept: "image/" %>
                      </div>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary font-weight-bold" data-dismiss="modal">Close</button>
                      <%= f.submit "Edit", class:"btn btn-success font-weight-bold" %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div style="color: #6169d0;"><%= paginate @posts %></div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">共有事項を投稿する</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <%= form_for @post, url:  posts_path do |f| %>
            <div class="modal-body">
              <div class="form-group">
                <%= f.label :title, "タイトル" %>
                <%= f.text_field :title, class:"form-control" %>
              </div>
              <div class="form-group">
                <%= f.label :appeal, "アピールポイント" %>
                <%= f.text_area :appeal, rows:'10',placeholder: "自分の頑張ったところを紹介しよう" , class:"form-control"%>
              </div>
              <div class="form-group">
                <%= f.label :job, "役職" %>
                <%= f.text_field :job, class:"form-control" %>
              </div>
              <div class="form-group">
                <%= f.label :name, "担当者" %>
                <%= f.text_field :name, class:"form-control" %>
              </div>
              <div class="form-group">
                <%= f.label :ジャンル,class: "col-sm-3 col-form-label" %>
                <%= f.collection_select :tag_id, Tag.all, :id, :name, class: 'form-control'%>
              </div>
              <div class="form-group">
                <%= f.label :画像 ,class: "col-sm-3 col-form-label " %>
                <%= f.file_field :profile_image, accept: "image/" %>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary font-weight-bold" data-dismiss="modal">Close</button>
              <%= f.submit "Shere!!", class:"btn btn-primary font-weight-bold" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
</div>