config/routes.rb
Rails.application.routes.draw do

  root 'home#top'

  devise_for :shops,skip: [:passwords], controllers: {
    registrations: "shop/registrations",
    sessions: 'shop/sessions'
  }

  devise_for :managements,skip: [:passwords], controllers: {
    registrations: "management/registrations",
    sessions: 'management/sessions'
  }

  devise_scope :shop do
    post 'shops/guest_sign_in', to: 'shops/sessions#guest_sign_in'
  end

  devise_scope :management do
    post 'managements/guest_sign_in', to: 'managements/sessions#guest_sign_in'
  end

  scope module: :shop do
    resources :notifications, only: :index do
        delete "all_destroy"
      end
    resources :shops, only: [:edit, :update] do
      collection do
        get "my_page" => "shops#show"
      end
    end
    resources :posts do
      resources :comment_reviews, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      collection do
        get "search"
      end
    end
    resources :groups do
      get "join" => "groups#join"
      get "new/mail" => "groups#new_mail"
      get "send/mail" => "groups#send_mail"
      delete "all_destroy" => "groups#all_destroy"
    end
    resources :mother_father_gifts
    resources :summer_gifts
    resources :year_end_gifts
    resources :day_of_the_oxes
    resources :ehomakis
    resources :christmases
    get "chat/:id" => "chats#show", as: "chat"
    resources :chats, only: [:create]
  end

    namespace :management do
      resources :managements, only: [:edit, :update] do
        collection do
          get "my_page" => "managements#show"
        end
      end
      resources :posts do
        resource :management_favorites, only: [:create, :destroy]
      end
    end
end

app/controllers/shop/chats_controller.rb
class Shop::ChatsController < ApplicationController
  before_action :authenticate_shop!

  def show
    @shop = Shop.find(params[:id])
    rooms = current_shop.shop_rooms.pluck(:room_id)
    shop_rooms = ShopRoom.find_by(shop_id: @shop.id,room_id: rooms)

    unless shop_rooms.nil?
      @room = shop_rooms.room
    else
      @room = Room.new
      @room.save
      ShopRoom.create(shop_id: current_shop.id, room_id: @room.id)
      ShopRoom.create(shop_id: @shop.id, room_id: @room.id)
    end
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end

  def create
    @chat = current_shop.chats.new(chat_params)
    if @chat.save
      @chat.create_notification_chat!(current_shop, @chat.id, @chat.room_id, @chat.room.shop_rooms.where.not(shop_id: current_shop.id).first.shop_id)
      redirect_to request.referer
    else
      redirect_to request.referer,alert: "メッセージを入力してください"
    end
  end

  private

  def chat_params
    params.require(:chat).permit(:message, :room_id, images: [] )
  end

end

app/controllers/shop/christmases_controller.rb
class Shop::ChristmasesController < ApplicationController
  before_action :user_authenticate

  def index

    @christmas = Christmas.new
    @shop_total_amount = 0
    @shop_tptal_booking_target = 0
    @shop_store_sales_amount = 0

    @current_year = params[:current_year].present? ? params[:current_year] : Time.zone.now.year
    @all_christmases = Christmas.all
    @christmases = @all_christmases.where(year: @current_year)
    @christmases = @christmases.order(booking_amount: :asc) if params[:sort_amount] == "booking_amount_asc"
    @christmases = @christmases.order(total_amount: :asc) if params[:sort_amount] == "total_amount_asc"
    @christmases = @christmases.order(booking_amount: :desc) if params[:sort_amount] == "booking_amount_desc"
    @christmases = @christmases.order(total_amount: :desc) if params[:sort_amount] == "total_amount_desc"
    @christmases = @christmases.page(params[:page])

  end

  def create
    @christmas = Christmas.new(christmas_params)
    @christmas.shop_id = current_shop.id
    if @christmas.save
      redirect_to christmases_path, notice: "投稿に成功しました"
    else
      @shop_total_amount = 0
      @shop_tptal_booking_target = 0
      @shop_store_sales_amount = 0

      @current_year = params[:current_year].present? ? params[:current_year] : Time.zone.now.year
      @all_christmases = Christmas.all
      @christmases = @all_christmases.where(year: @current_year)
      @christmases = @christmases.order(booking_amount: :asc) if params[:sort_amount] == "booking_amount_asc"
      @christmases = @christmases.order(total_amount: :asc) if params[:sort_amount] == "total_amount_asc"
      @christmases = @christmases.order(booking_amount: :desc) if params[:sort_amount] == "booking_amount_desc"
      @christmases = @christmases.order(total_amount: :desc) if params[:sort_amount] == "total_amount_desc"
      @christmases = @christmases.page(params[:page])
      render :index
    end
  end

  def update
    @christmas = Christmas.find(params[:id])
    if @christmas.update(christmas_params)
      redirect_to christmases_path, notice: "投稿を更新しました"
    else
      @shop_total_amount = 0
      @shop_tptal_booking_target = 0
      @shop_store_sales_amount = 0

      @current_year = params[:current_year].present? ? params[:current_year] : Time.zone.now.year
      @all_christmases = Christmas.all
      @christmases = @all_christmases.where(year: @current_year)
      @christmases = @christmases.order(booking_amount: :asc) if params[:sort_amount] == "booking_amount_asc"
      @christmases = @christmases.order(total_amount: :asc) if params[:sort_amount] == "total_amount_asc"
      @christmases = @christmases.order(booking_amount: :desc) if params[:sort_amount] == "booking_amount_desc"
      @christmases = @christmases.order(total_amount: :desc) if params[:sort_amount] == "total_amount_desc"
      @christmases = @christmases.page(params[:page])
      render :index
    end
  end

  def destroy
    @christmas = Christmas.find(params[:id])
    @christmas.destroy
    redirect_to christmases_path, notice: "投稿を削除しました"
  end


  def edit
    @christmas = Christmas.find(params[:id])
  end

  private

  def user_authenticate
    if shop_signed_in? || management_signed_in?
    else
      redirect_to root_path
    end
  end


  def christmas_params
    params.require(:christmas).permit(:year, :booking_target,:booking_amount, :target_amount,  :store_sales_amount, :total_amount, :shop_id, :ff_amount)
  end
end

app/controllers/shop/comment_reviews_controller.rb
class Shop::CommentReviewsController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    comment = current_management.comment_reviews.new(comment_review_params)
    comment.post_id = post.id
    comment.save
    redirect_to post_path(post), notice: "コメントの投稿に成功しました"
  end

  def destroy
    CommentReview.find(params[:id]).destroy
    redirect_to post_path(params[:post_id]), notice: "コメントを削除しました"
  end

  private

  def comment_review_params
    params.require(:comment_review).permit(:comment, :star)
  end
end

app/controllers/shop/confirmations_controller.rb
# frozen_string_literal: true

class Shop::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/shop/day_of_the_oxes_controller.rb
class Shop::DayOfTheOxesController < ApplicationController
  before_action :user_authenticate
  
  def index

    @day_of_the_ox = DayOfTheOx.new
    @shop_total_amount = 0
    @shop_tptal_booking_target = 0
    @shop_store_sales_amount = 0

    @current_year = params[:current_year].present? ? params[:current_year] : Time.zone.now.year
    @all_day_of_the_oxes = DayOfTheOx.all
    @day_of_the_oxes = @all_day_of_the_oxes.where(year: @current_year)
    @day_of_the_oxes = @day_of_the_oxes.order(booking_amount: :asc) if params[:sort_amount] == "booking_amount_asc"
    @day_of_the_oxes = @day_of_the_oxes.order(total_amount: :asc) if params[:sort_amount] == "total_amount_asc"
    @day_of_the_oxes = @day_of_the_oxes.order(booking_amount: :desc) if params[:sort_amount] == "booking_amount_desc"
    @day_of_the_oxes = @day_of_the_oxes.order(total_amount: :desc) if params[:sort_amount] == "total_amount_desc"
    @day_of_the_oxes = @day_of_the_oxes.page(params[:page])
  end

  def create
    @day_of_the_ox = DayOfTheOx.new(day_of_the_ox_params)
    @day_of_the_ox.shop_id = current_shop.id
    if @day_of_the_ox.save
      redirect_to day_of_the_oxes_path, notice: "投稿に成功しました"
    else
      @shop_total_amount = 0
      @shop_tptal_booking_target = 0
      @shop_store_sales_amount = 0

      @current_year = params[:current_year].present? ? params[:current_year] : Time.zone.now.year
      @all_day_of_the_oxes = DayOfTheOx.all
      @day_of_the_oxes = @all_day_of_the_oxes.where(year: @current_year)
      @day_of_the_oxes = @day_of_the_oxes.order(booking_amount: :asc) if params[:sort_amount] == "booking_amount_asc"
      @day_of_the_oxes = @day_of_the_oxes.order(total_amount: :asc) if params[:sort_amount] == "total_amount_asc"
      @day_of_the_oxes = @day_of_the_oxes.order(booking_amount: :desc) if params[:sort_amount] == "booking_amount_desc"
      @day_of_the_oxes = @day_of_the_oxes.order(total_amount: :desc) if params[:sort_amount] == "total_amount_desc"
      @day_of_the_oxes = @day_of_the_oxes.page(params[:page])
      render :index
    end
  end

  def update
    @day_of_the_ox = DayOfTheOx.find(params[:id])
    if @day_of_the_ox.update(day_of_the_ox_params)
      redirect_to day_of_the_oxes_path, notice: "投稿を更新しました"
    else
      @shop_total_amount = 0
      @shop_tptal_booking_target = 0
      @shop_store_sales_amount = 0

      @current_year = params[:current_year].present? ? params[:current_year] : Time.zone.now.year
      @all_day_of_the_oxes = DayOfTheOx.all
      @day_of_the_oxes = @all_day_of_the_oxes.where(year: @current_year)
      @day_of_the_oxes = @day_of_the_oxes.order(booking_amount: :asc) if params[:sort_amount] == "booking_amount_asc"
      @day_of_the_oxes = @day_of_the_oxes.order(total_amount: :asc) if params[:sort_amount] == "total_amount_asc"
      @day_of_the_oxes = @day_of_the_oxes.order(booking_amount: :desc) if params[:sort_amount] == "booking_amount_desc"
      @day_of_the_oxes = @day_of_the_oxes.order(total_amount: :desc) if params[:sort_amount] == "total_amount_desc"
      @day_of_the_oxes = @day_of_the_oxes.page(params[:page])
      render :index
    end
  end

  def destroy
    @day_of_the_ox = DayOfTheOx.find(params[:id])
    @day_of_the_ox.destroy
    redirect_to day_of_the_oxes_path, notice: "投稿を削除しました"
  end

  private
  
  def user_authenticate
    if shop_signed_in? || management_signed_in?
    else
      redirect_to root_path
    end
  end
  
  def day_of_the_ox_params
    params.require(:day_of_the_ox).permit(:year, :booking_target,:booking_amount, :target_amount,  :store_sales_amount, :total_amount, :shop_id)
  end
end

app/controllers/shop/ehomakis_controller.rb
class Shop::EhomakisController < ApplicationController
  before_action :user_authenticate

  def index

    @ehomaki = Ehomaki.new
    @shop_total_amount = 0
    @shop_tptal_booking_target = 0
    @shop_store_sales_amount = 0

    @current_year = params[:current_year].present? ? params[:current_year] : Time.zone.now.year
    @all_ehomakis = Ehomaki.all
    @ehomakis = @all_ehomakis.where(year: @current_year)
    @ehomakis = @ehomakis.order(booking_amount: :asc) if params[:sort_amount] == "booking_amount_asc"
    @ehomakis = @ehomakis.order(total_amount: :asc) if params[:sort_amount] == "total_amount_asc"
    @ehomakis = @ehomakis.order(booking_amount: :desc) if params[:sort_amount] == "booking_amount_desc"
    @ehomakis = @ehomakis.order(total_amount: :desc) if params[:sort_amount] == "total_amount_desc"
    @ehomakis = @ehomakis.page(params[:page])
  end

  def create
    @ehomaki = Ehomaki.new(ehomaki_params)
    @ehomaki.shop_id = current_shop.id
    if @ehomaki.save
      redirect_to ehomakis_path, notice: "投稿に成功しました"
    else

      @shop_total_amount = 0
      @shop_tptal_booking_target = 0
      @shop_store_sales_amount = 0

      @current_year = params[:current_year].present? ? params[:current_year] : Time.zone.now.year
      @all_ehomakis = Ehomaki.all
      @ehomakis = @all_ehomakis.where(year: @current_year)
      @ehomakis = @ehomakis.order(booking_amount: :asc) if params[:sort_amount] == "booking_amount_asc"
      @ehomakis = @ehomakis.order(total_amount: :asc) if params[:sort_amount] == "total_amount_asc"
      @ehomakis = @ehomakis.order(booking_amount: :desc) if params[:sort_amount] == "booking_amount_desc"
      @ehomakis = @ehomakis.order(total_amount: :desc) if params[:sort_amount] == "total_amount_desc"
      @ehomakis = @ehomakis.page(params[:page])
      render :index
    end
  end

  def update
    @ehomaki = Ehomaki.find(params[:id])
    if @ehomaki.update(ehomaki_params)
      redirect_to ehomakis_path, notice: "投稿を更新しました"
    else

      @shop_total_amount = 0
      @shop_tptal_booking_target = 0
      @shop_store_sales_amount = 0

      @current_year = params[:current_year].present? ? params[:current_year] : Time.zone.now.year
      @all_ehomakis = Ehomaki.all
      @ehomakis = @all_ehomakis.where(year: @current_year)
      @ehomakis = @ehomakis.order(booking_amount: :asc) if params[:sort_amount] == "booking_amount_asc"
      @ehomakis = @ehomakis.order(total_amount: :asc) if params[:sort_amount] == "total_amount_asc"
      @ehomakis = @ehomakis.order(booking_amount: :desc) if params[:sort_amount] == "booking_amount_desc"
      @ehomakis = @ehomakis.order(total_amount: :desc) if params[:sort_amount] == "total_amount_desc"
      @ehomakis = @ehomakis.page(params[:page])
      render :index
    end
  end

  def destroy
    @ehomaki = Ehomaki.find(params[:id])
    @ehomaki.destroy
    redirect_to ehomakis_path, notice: "投稿を削除しました"
  end

  private

  def user_authenticate
    if shop_signed_in? || management_signed_in?
    else
      redirect_to root_path
    end
  end

  def ehomaki_params
    params.require(:ehomaki).permit(:year, :booking_target,:booking_amount, :target_amount,  :store_sales_amount, :total_amount, :shop_id)
  end
end

app/controllers/shop/favorites_controller.rb
class Shop::FavoritesController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    favorite = current_shop.favorites.new(post_id: @post.id)
    favorite.save
  end


  def destroy
    @post = Post.find(params[:post_id])
    favorite = current_shop.favorites.find_by(post_id: @post.id)
    favorite.destroy
  end

end

app/controllers/shop/groups_controller.rb
class Shop::GroupsController < ApplicationController
  before_action :authenticate_shop!

  def index
    @groups = Group.all
    @group = Group.new
  end

  def create
    @group = current_shop.owned_groups.new(group_params)
    @group.owner_id = current_shop.id
    @group.shops << current_shop  # @group.shops << current_shop  @group.shopsに追加しているという記述
    if @group.save
      redirect_to groups_path(@group), notice: "グループ作成に成功しました"
    else
      @groups = Group.all
      render :index
    end
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to groups_path, notice: "グループ情報を更新しました"
    else
      render :index
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.shops.delete(current_shop)
    redirect_to groups_path
  end


  def join
    @group = Group.find(params[:group_id])
    @group.shops << current_shop
    redirect_to groups_path
  end

  def all_destroy
    @group = Group.find(params[:group_id])
    if @group.destroy
      redirect_to groups_path, notice: "グループを削除しました"
    end
  end

  def new_mail
    @group = Group.find(params[:id])
  end

  def send_mail
    @group = Group.find(params[:group_id])
    group_shops = @group.shops
    @mail_title = params[:title]
    @mail_content = params[:content]
    ContactMailer.send_mail(@mail_title, @mail_content, group_shops).deliver
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :profile_image, :status)
  end

end

app/controllers/shop/notifications_controller.rb
class Shop::NotificationsController < ApplicationController
  def index
    @notifications = current_shop.passive_notifications.all
    @notifications.where(checked: false).each do |notification|
      notification.update_attribute(:checked, true)
    end
  end

  def all_destroy
    @notifications = current_shop.passive_notifications.all
    @notifications.destroy_all
    redirect_to notifications_path, notice: "通知を全て削除しました"
  end


end

app/controllers/shop/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Shop::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/views/shop/mother_father_gifts/index.html.erb
<div class="d-flex flex-row w-100" style="height: calc(100% - 50px)">
  <!--サイドバーコンテンツ-->
  <%= render "layouts/sidenav" %>
    <div class="container mt-5">
      <div class="row">
        <div class="col">
          <% if  @mother_father_gift.errors.any? %>
           <ul class=" alert alert-danger">
              <%= @mother_father_gift.errors.count %>件のエラーが発生しました
              <% @mother_father_gift.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
          <div class="row">
            <div class="col-4 col-lg-4 col-md-4 col-sm-4">
              <% if shop_signed_in? %>
              <div data-toggle="tooltip" title="報告する">
                <button type="button" class="btn btn-primary  btn-block mb-3 mr-4  font-weight-bold" data-toggle="modal" data-target="#exampleModal">
                  Report!!
                </button>
              </div>
              <% end %>
            </div>
            <div class="col-12 col-lg-4 col-md-12 col-sm-12">
              <span class=" font-weight-bold " style=" color: #6169d0; ">母の日父の日ギフト実績(全店舗合計)</span>
            </div>
          </div>
          <% @mother_father_gifts.each do |gift| %>
            <% @shop_total_target_number += gift.target_number %>
            <% @shop_tptal_target_amount += gift.target_amount %>
            <% @shop_total_number += gift.number %>
            <% @shop_total_amount += gift.total_amount %>
          <% end %>
          <div class="mb-2 bg-white p-3 shadow-sm  text-secondary font-weight-bold">
            目標合計件数:<%= @shop_total_target_number.to_s(:delimited) %>件
            目標合計金額:<%= @shop_tptal_target_amount.to_s(:delimited) %>円
            合計件数:<%= @shop_total_number.to_s(:delimited) %>件
            合計達成金額:<%= @shop_total_amount.to_s(:delimited) %>円
          </div>
          <%= form_with(url: mother_father_gifts_path, method: :get, local: true) do |f| %>
            <%= f.select :sort_amount,  { "件数▼" => :number_asc,
                                          "件数▲" => :number_desc,
                                          "達成金額▼" => :total_amount_asc,
                                          "達成金額▲" => :total_amount_desc },
                                          { include_blank: "登録順", selected: params[:sort_amount] }, {class: "text-secondary font-weight-bold"} %>
            <%= f.submit "Change",class:"pt-1 pb-1 rounded border-0 font-weight-bold", style:"background-color: #888b8e; color: #ffffff;"%>
          <% end %>
          <% if @all_mother_father_gifts.where(year: @current_year.to_i + 1).any? %>
            <%= link_to mother_father_gifts_path(current_year: (@current_year.to_i + 1)) ,class: "text-secondary font-weight-bold  text-decoration-none" do %>
              来年 <i class="fas fa-arrow-circle-right"></i>
            <% end %>
          <% end %>
          <% if @all_mother_father_gifts.where(year: @current_year.to_i - 1).any? %>
            <%= link_to mother_father_gifts_path(current_year: (@current_year.to_i - 1)) ,class: "text-secondary font-weight-bold  text-decoration-none" do%>
              <i class="fas fa-arrow-circle-left"></i> 前年
            <% end %>
          <% end %>
          <table class="table text-secondary font-weight-bold">
            <% @mother_father_gifts.each do |gift| %>
              <tr>
                <td>
                  <%= gift.shop.name %><br>
                  <%=  gift.year %>年度
                </td>
                <td>目標件数:<%=  gift.target_number %>件</td>
                <td>目標金額:<%=  gift.target_amount.to_s(:delimited) %>円</td>
                <td>件数:<%=  gift.number %>件</td>
                <td>達成金額:<%=  gift.total_amount.to_s(:delimited) %>円</td>
                <td>
                  <% if shop_signed_in? %>
                    <% if gift.shop_id == current_shop.id %>
                      <td>
                        <span data-toggle="tooltip" data-placement="bottom" title="編集する" ><span class=" rounded-circle p-2 shadow-sm mr-3"style="background-color: #ffffff;"data-toggle="modal" data-target="#exampleModal_<%= gift.id %>"><i class="fas fa-edit"  style=" color: #6169d0; "></i></span></span>
                        <%= link_to  mother_father_gift_path(gift), method: :delete,"data-confirm" => "本当に消しますか？" do %>
                          <span data-toggle="tooltip" data-placement="bottom" title="削除する" ><span class="bg-white rounded-circle p-2 shadow-sm"><i class="fas fa-eraser" style=" color: #6169d0; "></i></span></span>
                        <% end %>
                      </td>
                    <% end %>
                  <% end %>
                </td>
              </tr>
              <!-- Modal -->
              <div class="modal fade" id="exampleModal_<%= gift.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">実績報告を修正する</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <%= form_with model: gift, url: mother_father_gift_path(gift) do |f| %>
                      <div class="modal-body">
                        <div class="form-group">
                          <%= f.label :year, "年度" %>
                          <%= f.text_field :year, class:"form-control" %>
                        </div>
                        <div class="form-group">
                          <%= f.label :taget_number, "目標件数" %>
                          <%= f.text_field :target_number, class:"form-control" %>
                        </div>
                        <div class="form-group">
                          <%= f.label :target_amount, "目標金額" %>
                          <%= f.text_field :target_amount, class:"form-control" %>
                        </div>
                        <div class="form-group">
                          <%= f.label :number, "件数" %>
                          <%= f.text_field :number, class:"form-control" %>
                        </div>
                        <div class="form-group">
                          <%= f.label :total_amount, "達成金額" %>
                          <%= f.text_field :total_amount, class:"form-control" %>
                        </div>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary font-weight-bold" data-dismiss="modal">Close</button>
                        <%= f.submit "Edit", class:"btn btn-success font-weight-bold" %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          </table>
          <div style="color: #6169d0;"><%= paginate @mother_father_gifts %></div>
        </div>
      </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">母の日父の日ギフト実績報告</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <%= form_for @mother_father_gift, url: mother_father_gifts_path do |f| %>
            <div class="modal-body">
              <div class="form-group">
                <%= f.label :year, "年度" %>
                <%= f.text_field :year, class:"form-control" %>
              </div>
              <div class="form-group">
                <%= f.label :taget_number, "目標件数" %>
                <%= f.text_field :target_number, class:"form-control" %>
              </div>
              <div class="form-group">
                <%= f.label :target_amount, "目標金額" %>
                <%= f.text_field :target_amount, class:"form-control" %>
              </div>
              <div class="form-group">
                <%= f.label :number, "件数" %>
                <%= f.text_field :number, class:"form-control" %>
              </div>
              <div class="form-group">
                <%= f.label :total_amount, "達成金額" %>
                <%= f.text_field :total_amount, class:"form-control" %>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary font-weight-bold" data-dismiss="modal">Close</button>
              <%= f.submit "Report!!", class:"btn btn-primary font-weight-bold" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
</div>