config/routes.rb
Rails.application.routes.draw do

  root 'home#top'

  devise_for :shops,skip: [:passwords], controllers: {
    registrations: "shop/registrations",
    sessions: 'shop/sessions'
  }

  devise_for :managements,skip: [:passwords], controllers: {
    registrations: "management/registrations",
    sessions: 'management/sessions'
  }

  devise_scope :shop do
    post 'shops/guest_sign_in', to: 'shops/sessions#guest_sign_in'
  end

  devise_scope :management do
    post 'managements/guest_sign_in', to: 'managements/sessions#guest_sign_in'
  end

  scope module: :shop do
    resources :notifications, only: :index do
        delete "all_destroy"
      end
    resources :shops, only: [:edit, :update] do
      collection do
        get "my_page" => "shops#show"
      end
    end
    resources :posts do
      resources :comment_reviews, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      collection do
        get "search"
      end
    end
    resources :groups do
      get "join" => "groups#join"
      get "new/mail" => "groups#new_mail"
      get "send/mail" => "groups#send_mail"
      delete "all_destroy" => "groups#all_destroy"
    end
    resources :mother_father_gifts
    resources :summer_gifts
    resources :year_end_gifts
    resources :day_of_the_oxes
    resources :ehomakis
    resources :christmases
    get "chat/:id" => "chats#show", as: "chat"
    resources :chats, only: [:create]
  end

    namespace :management do
      resources :managements, only: [:edit, :update] do
        collection do
          get "my_page" => "managements#show"
        end
      end
      resources :posts do
        resource :management_favorites, only: [:create, :destroy]
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/top.html.erb
<main style="background-color: #313a46;">
  <div class="container-fluid text-justify">
    <div class="row ">
      <div class="col-12 d-block d-sm-none">
        <img src= <%= asset_path'PF.jpg' %> class="img-fluid"alt="Responsive image">
      </div>
      <div class="col-12 d-none d-sm-block">
        <img src= <%= asset_path'PF2.jpg' %> class="img-fluid"alt="Responsive image">
      </div>
    </div>
  </div>
</main>
<div class="container mt-2">
  <div class="row d-flex justify-content-center">
    <div class="col">
      <div class="pagination justify-content-center">
        <%=  link_to  new_shop_registration_path ,class: "text-decoration-none" do %>
          <button type="button" class="btn btn-primary font-weight-bold  d-none d-sm-block"style=" min-height: 60px;"><i class="fas fa-plus-circle"></i> Shop SignUp!</button>
        <% end %>
        <%=  link_to  new_shop_session_path ,class: "text-decoration-none" do %>
          <button type="button" class="btn btn-primary font-weight-bold  ml-1"style=" min-height: 60px;"><i class="fas fa-sign-in-alt"></i> Shop LogIn!</button>
        <% end %>
        <%=  link_to  new_management_registration_path,class: "text-decoration-none" do %>
          <button type="button" class="btn btn-primary font-weight-bold  d-none d-sm-block ml-1"style=" min-height: 60px;"><i class="fas fa-plus-circle"></i> Management SignUp!</button>
        <% end %>
        <%=  link_to  new_management_session_path,class: "text-decoration-none" do %>
          <button type="button" class="btn btn-primary font-weight-bold  ml-1"style=" min-height: 60px;"><i class="fas fa-sign-in-alt"></i> Management LogIn!</button>
        <% end %>
         <%= link_to shops_guest_sign_in_path, method: :post ,class: "text-decoration-none" do %>
          <button type="button" class="btn btn-warning font-weight-bold  d-none d-sm-block ml-1"style=" min-height: 60px;"><i class="fas fa-sign-in-alt"></i> GestShop LogIn!</button>
        <% end %>
        <%= link_to managements_guest_sign_in_path, method: :post ,class: "text-decoration-none" do %>
          <button type="button" class="btn btn-warning font-weight-bold  d-none d-sm-block ml-1"style=" min-height: 60px;"><i class="fas fa-sign-in-alt"></i> GestManagement LogIn!</button>
        <% end %>
      </div>
    </div>
    <div class="row mt-2">
      <div class="col">
        <%=  link_to  new_shop_registration_path ,class: "text-decoration-none" do %>
          <button type="button" class="btn btn-warning font-weight-bold d-sm-none"style=" min-height: 60px;"><i class="fas fa-plus-circle"></i> Shop SignUp!</button>
        <% end %>
        <%=  link_to  new_management_registration_path,class: "text-decoration-none" do %>
          <button type="button" class="btn btn-warning font-weight-bold  d-sm-none"style=" min-height: 60px;"><i class="fas fa-plus-circle"></i> Management SignUp!</button>
        <% end %>
      </div>
    </div>
  </div>
</div>